spring:
  datasource:
    # url
    url: jdbc:h2:tcp://localhost/~/schedule
    # db name
    username: sa
    # db password
    password:
    # db driver
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
