spring:
  datasource:
    # url
    url: jdbc:h2:tcp://localhost/~/schedule
    # db name
    username: sa
    # db password
    password:
    # db driver
    driver-class-name: org.h2.Driver

  jpa:
    # hibernate
    hibernate:
      ddl-auto: create
    properties:
      show_sql: true
      format_sql: true
    generate-ddl: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
